server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liBxcYzidMb4tXdj
            client-secret: 13d9ffc58e1547bea08c03726c823579c799a587
            scope: read:user, user:email
            redirect-uri: "http://localhost:8082/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user